// <auto-generated />
namespace MarvelCatalog_App.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Iaddednewuserfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Iaddednewuserfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201710051209306_I added new user fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
